---
# reference: https://cirrus-ci.org/guide/writing-tasks/
container:
  cpu: 1
  memory: "2G"

lint_markdown_task:
  name: "Lint Markdown"
  container:
    image: "docker.io/library/node:latest"
  install_script: "npm install -g markdownlint-cli"
  lint_script: "markdownlint *.md docs/*.md"

lint_yaml_task:
  name: "Lint YAML"
  container:
    image: "docker.io/library/alpine:latest"
  install_script: "apk add --no-cache yamllint"
  lint_script: "yamllint ."

lint_containerfile_task:
  name: "Lint Containerfile"
  container:
    image: "docker.io/hadolint/hadolint:latest-alpine"
  test_script: "hadolint container/Dockerfile"

scan_containerfile_task:
  name: "Scan Containerfile"
  container:
    image: "docker.io/aquasec/trivy:0.22.0"
  scan_script: "trivy config
                --severity CRITICAL
                --exit-code 1
                container/"
...
