---
# https://github.com/arc-community/arc/blob/master/.pre-commit-config.yaml
# https://github.com/pre-commit/pre-commit-hooks
# https://pre-commit.ci/
# pre-commit and pyproject.toml
# https://github.com/pre-commit/pre-commit/issues/1165#issuecomment-862603032
# pre-commit will look for .pre-commit-hooks.yaml in specified repos
# SKIP=<hook1>,<hook2> ...
# https://pre-commit.com/#temporarily-disabling-hooks
#
# TODO black, isort, flake8 may not load the config files from root
#
exclude: '.bumpversion.cfg'

default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key
  - id: check-ast
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-docstring-first
  # - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-yaml
  # - id: check-json
  # - id: pretty-format-json
  - id: check-toml
  # forbid utf-8 BOM
  # deprecated: check-byte-order-marker
  - id: fix-byte-order-marker
  - id: trailing-whitespace
  - id: end-of-file-fixer
  # debugger imports and breackpoint()
  - id: debug-statements
  # - id: mixed-line-ending
  # - id: check-json
  # - id: check-yaml

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    # additional_dependencies: [black==latest]

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8

# https://pypi.org/project/interrogate/
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0  # or master if you're bold
  hooks:
    - id: interrogate
      args: [--quiet, --fail-under=95]

# pre-commit runs mypy from an isolated virtualenv
# has no access to cfg and pkgs
# args and deps may have to be added here again
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
    args: [--no-strict-optional, --ignore-missing-imports]
    # additional_dependencies: [tokenize-rt==3.2.0]

- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
    args: [--py37-plus]

# use on pre-commit-hooks?
#
# - id: hadolint-docker
#   name: Lint Dockerfiles
#   description: Runs hadolint Docker image to lint Dockerfiles
#   language: docker_image
#   types: ["dockerfile"]
#   entry: ghcr.io/hadolint/hadolint hadolint
# - id: hadolint
#   name: Lint Dockerfiles
#   description: Runs hadolint to lint Dockerfiles
#   language: system
#   types: ["dockerfile"]
#   entry: hadolint
...
