---
datasets:
  yahoo:
    dataset: "yahoo_answers_topics"
    configuration: ""
    average: "micro"
    col_to_rename: "topic"
    cols_to_tokenize:
      - "question_title"
    cols_to_remove:
      - "id"
      - "question_content"
      - "best_answer"
  mrpc:
    dataset: "glue"
    configuration: "mrpc"
    average: "binary"
    col_to_rename: "label"
    cols_to_tokenize:
      - "sentence1"
      - "sentence2"
    cols_to_remove:
      - "idx"
  mnli:
    dataset: "glue"
    configuration: "mnli"
    average: "binary"
    col_to_rename: "label"
    cols_to_tokenize:
      - "premise"
      - "hypothesis"
    cols_to_remove:
      - "idx"
models:
  dbbu:
    name: "BERT"
    full_name: "distilbert-base-uncased"
  bbu:
    name: "BERT"
    full_name: "bert-base-uncased"
  lbu:
    name: "LONGFORMER"
    full_name: "allenai/longformer-base-4096"
metrics_to_optimize:
  accuracy:
    goal: "maximize"
    greater_is_better: true
  loss:
    goal: "minimize"
    greater_is_better: false
  eval_loss:
    goal: "minimize"
    greater_is_better: false
metrics_secondary_possible:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "mae"
    - "mse"
...
